### ISSUE TITLE
Doesn't look like it works for me

### ISSUE THREAD

**Issue by thecosmicfrog** [anamritraj/google-photos-plus#2]
Hi there,

Nice work on creating this but, in my testing, this does not seem to work for me. In fact, the photos that Photos+ is downloading appear to be of a lower quality (at least according to the metrics). I've also noticed that Photos+ is stripping out a lot of useful JPEG metadata. Take a look at my outputs below.

In this example, **orig** is the standard version using the _Download_ button from Google Photos. **better** is the apparent higher quality version from the Photos+ download button.
Notice the **File size** and **JPEG Quality** fields.

```
# jhead command gets the JPEG metadata
$> jhead IMG_1234_orig.JPG > metadata_orig.txt
$> jhead IMG_1234_better.JPG > metadata_better.txt

$> diff -y metadata_orig.txt metadata_better.txt
File name    : IMG_1234_orig.JPG		      |	File name    : IMG_1234_better.JPG
File size    : 7546221 bytes				      |	File size    : 2967754 bytes
File date    : 2019:01:01 01:23:45			      |	File date    : 2019:01:01 01:23:45
Camera make  : Canon					      <
Camera model : Canon EOS 760D				      <
Date/Time    : 2019:01:01 01:23:45			      <
Resolution   : 6000 x 4000					Resolution   : 6000 x 4000
Flash used   : No					      |	JPEG Quality : 90
Focal length : 18.0mm  (35mm equivalent: 29mm)		      <
CCD width    : 22.68mm					      <
Exposure time: 0.0020 s  (1/500)			      <
Aperture     : f/8.0					      <
ISO equiv.   : 100					      <
Whitebalance : Auto					      <
Metering Mode: pattern					      <
Exposure     : aperture priority (semi-auto)		      <
GPS Latitude : <redacted>					      <
GPS Longitude: <redacted>					      <
JPEG Quality : 97					      <
```

Likewise, the filesize is much smaller in the "better" version.

```
$> du -h IMG_1234_orig.JPG IMG_1234_better.JPG 
7.2M	IMG_1234_orig.JPG
2.9M	IMG_1234_better.JPG
```

Perhaps something has since changed in the way Google Photos handles downloads? Apologies - I did not get to try this extension when it was first released, so I have no point of comparison.

Best wishes,
Aaron

**Comment by anamritraj** [comment]
By any chance are you using a Pixel phone?

**Comment by thecosmicfrog** [comment]
@anamritraj Yes, I use a Pixel phone. But the image example above was for a Canon DSLR photo that I uploaded to Google Photos.

**Comment by anamritraj** [comment]
Hmmm... 

I have seen that when using Google Camera on Pixel phones or even using modded [Google Camera APKs on other phones](https://forum.xda-developers.com/apps/google-camera-mods/oneplus-6-google-camera-port-t3797544) (I used it on my OnePlus 6), Google Photos uploads the images in almost original quality and in that case this extension does not seem to make any difference. But only in cases when people use pixel phones. 

I have never seen it happening for any other phones. It is possible that since your account is associated with a Pixel device, [Google is giving you original quality uploads](https://9to5google.com/2018/10/10/google-pixel-unlimited-photos-backup-for-life/) even though the photos are not taken from the Pixel phone. 

I am open to suggestions, if you have any, to fix this issue! Anyways thank you for taking the time out to try this extension and reporting this issue.

Cheers!

**Comment by thecosmicfrog** [comment]
No bother! Just wanted to mention it in case it helped you find or fix anything. All the best.
